// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ovxsgfcdzknpzxwrjjhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92eHNnZmNkemtucHp4d3JqamhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3OTUyNDgsImV4cCI6MjA4MzM3MTI0OH0.xvdwkgpNc8o0sUQA1zlq06QyeY3jVaerLDYxKSzxYgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);